### ISSUE TITLE
Settings completely broken, nothing can be configured

### ISSUE THREAD

**Issue by micheljung** [adrianoamalfi/hassos-addons#45]
**Describe the bug**

No options are available, no backup can be configured.

![image](https://github.com/adrianoamalfi/hassos-addons/assets/1864183/4467e8fb-89c4-407c-8049-9765ffe9eff5)

![image](https://github.com/adrianoamalfi/hassos-addons/assets/1864183/bff0688a-5d9b-455e-94ff-6c159280c31b)

![image](https://github.com/adrianoamalfi/hassos-addons/assets/1864183/e0ef7be8-0277-423b-bd1d-4bfe3aff038d)

![image](https://github.com/adrianoamalfi/hassos-addons/assets/1864183/16045ebd-0dda-4f0c-af15-d2ee69f6e304)

**To Reproduce**
I can't tell you how to reproduce, only what I remember I did:

1. Install the add-on on Homeassistant 2023.11.2
1. Open the UI
1. Maybe choose that you want multi-user
1. Maybe set a password
1. Change the theme to Dark
![image](https://github.com/adrianoamalfi/hassos-addons/assets/1864183/a1b79ced-2a20-4ce5-9c06-d8020ac241c6)
1. Save
1. Maybe restart
1. Open the UI: you get an HTTP 404
1. Re-Install the add-on
1. Now it's in the broken state and you have no idea what you did and how to fix it

**Expected behavior**
Don't break.

**Desktop (please complete the following information):**
Irrelevant, but Chrome on Windows 11.

---

How can I delete the settings to start from scratch?

**Comment by scheusal333** [comment]
same for me:
 Core 2024.1.2
Supervisor 2023.12.0
Operating System 11.3
Frontend 20240104.0

addon version: 0.1.11 

just installed the addon 2nd time.
I installed the addon and started it up, opend the web ui and did some setting changes like, setting a PW ...
did a restart and it didnt come up again.
reinstalled the addon and just left the settings unchanged.
then i tried to configure a backup an run into this issue where nothing is selectable, as [micheljung](https://github.com/micheljung) described

**Comment by adrianoamalfi** [comment]
I've updated the addon to version 0.1.12, which includes the update of Duplicati to version 2.0.7.100_canary, released on December 27, 2023. Please be aware that I am not an expert and I maintain this addon as a hobby. I would greatly appreciate it if those of you who are able could try modifying directly and submit a Pull Request. Your contributions would be immensely valuable. Please update to the latest version and verify if the issue still persists. Any feedback or additional problem reports would be very welcome.

**Comment by scheusal333** [comment]
I can confirm, its working again, thank you for the quick update.

**Comment by scheusal333** [comment]
This issue seems to be back, with the latest version 0.2.0 and HAos 2024.6.4
